# Generated by Django 3.2.13 on 2022-10-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_webservice', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Facultie'},
        ),
        migrations.AddField(
            model_name='grade',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gpa_webservice.department'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gpa_webservice.faculty'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-'), (10, 'D+'), (11, 'D'), (12, 'E'), (13, 'Absent')], default=13),
        ),
    ]
